spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:mysql://localhost:3310/libraryapi?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true