spring:
  application:
    name: libraryapi
  datasource:
    url: ${API_URL}
    username: ${API_USER}
    password: ${API_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect